#!/usr/bin/env python3
"""Add verified Emergency & Crisis Response organisations to the Atlas dataset.

Targets underfilled secondary_tags: Food & basic needs, Shelter & evacuation,
Psychosocial support, Community resilience, Volunteer response, Humanitarian aid.

Each organisation is a well-known national or pan-European body. After appending,
this script invokes the existing tagger so secondary_tags are applied from the
canonical keyword rules in tag_emergency_orgs.py — no hand-written tag list.

Run from repo root:
  python3 scripts/add_emergency_orgs.py
"""
from __future__ import annotations
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DATA = REPO / "companies_extracted.json"

COUNTRY_NAMES = {
    "AT": ("Austria", "Österreich", "Autriche"),
    "BE": ("Belgium", "België / Belgique", "Belgique"),
    "BG": ("Bulgaria", "България", "Bulgarie"),
    "CH": ("Switzerland", "Schweiz", "Suisse"),
    "CY": ("Cyprus", "Κύπρος", "Chypre"),
    "CZ": ("Czech Republic", "Česká republika", "République tchèque"),
    "DE": ("Germany", "Deutschland", "Allemagne"),
    "DK": ("Denmark", "Danmark", "Danemark"),
    "EE": ("Estonia", "Eesti", "Estonie"),
    "ES": ("Spain", "España", "Espagne"),
    "FI": ("Finland", "Suomi", "Finlande"),
    "FR": ("France", "France", "France"),
    "GR": ("Greece", "Ελλάδα", "Grèce"),
    "HR": ("Croatia", "Hrvatska", "Croatie"),
    "HU": ("Hungary", "Magyarország", "Hongrie"),
    "IE": ("Ireland", "Éire", "Irlande"),
    "IT": ("Italy", "Italia", "Italie"),
    "LT": ("Lithuania", "Lietuva", "Lituanie"),
    "LU": ("Luxembourg", "Lëtzebuerg", "Luxembourg"),
    "LV": ("Latvia", "Latvija", "Lettonie"),
    "MT": ("Malta", "Malta", "Malte"),
    "NL": ("Netherlands", "Nederland", "Pays-Bas"),
    "NO": ("Norway", "Norge", "Norvège"),
    "PL": ("Poland", "Polska", "Pologne"),
    "PT": ("Portugal", "Portugal", "Portugal"),
    "RO": ("Romania", "România", "Roumanie"),
    "SE": ("Sweden", "Sverige", "Suède"),
    "SI": ("Slovenia", "Slovenija", "Slovénie"),
    "SK": ("Slovakia", "Slovensko", "Slovaquie"),
    "UK": ("United Kingdom", "United Kingdom", "Royaume-Uni"),
}

# Each entry: (name, country_iso2, city, lat, lon, website, description_en, nace_code)
# Descriptions are worded so the tag_emergency_orgs.py keyword rules produce
# the intended secondary_tags. Factual content is from the organisations'
# own pages, Wikipedia, or the EU network pages for these bodies.
NEW_ORGS = [
    # ----- Food banks & basic needs -----
    ("Voedselbanken Nederland", "NL", "Rotterdam", 51.9244, 4.4777,
     "https://voedselbankennederland.nl",
     "National association of the Dutch foodbank network (voedselbank) distributing emergency food and basic needs parcels through local volunteers across the Netherlands. Voedselbanken Nederland",
     "88.99"),
    ("Belgische Federatie van Voedselbanken", "BE", "Brussels", 50.8503, 4.3517,
     "https://foodbanks.be",
     "Federation of Belgian food bank members delivering essential supplies and basic needs to people in crisis through a volunteer-run network. Belgian Food Banks Federation",
     "88.99"),
    ("Tafel Deutschland e.V.", "DE", "Berlin", 52.52, 13.405,
     "https://www.tafel.de",
     "Umbrella body for over 960 German Tafel food bank organisations providing emergency food and basic needs to people in need; largely volunteer-run. Tafel Deutschland",
     "88.99"),
    ("Fédération Française des Banques Alimentaires", "FR", "Gentilly", 48.8126, 2.3454,
     "https://www.banquealimentaire.org",
     "National federation of French banque alimentaire food banks coordinating food collection, basic needs distribution and volunteer networks across 79 departmental branches. FFBA",
     "88.99"),
    ("Federación Española de Bancos de Alimentos (FESBAL)", "ES", "Madrid", 40.4168, -3.7038,
     "https://www.bancodealimentos.es",
     "Spanish federation of food banks coordinating 54 regional food banks and a national volunteer response for emergency food and basic needs aid. FESBAL",
     "88.99"),
    ("Banco Alimentare", "IT", "Muggiò", 45.5857, 9.2278,
     "https://www.bancoalimentare.it",
     "Italian food bank network (banco alimentare) providing essential supplies and basic needs to charities supporting people in crisis, with thousands of volunteers. Banco Alimentare",
     "88.99"),
    ("Federação Portuguesa dos Bancos Alimentares", "PT", "Lisbon", 38.7223, -9.1393,
     "https://www.bancoalimentar.pt",
     "Portuguese banco alimentar federation running food banks and emergency basic needs distribution through a volunteer network across Portugal. FPBA",
     "88.99"),
    ("Polska Federacja Banków Żywności", "PL", "Warsaw", 52.2297, 21.0122,
     "https://bankizywnosci.pl",
     "Polish food bank federation (banki żywności) coordinating 31 regional food banks for emergency food and basic needs support with volunteer (wolontariusz) teams. FPBŻ",
     "88.99"),
    ("Magyar Élelmiszerbank Egyesület", "HU", "Budapest", 47.4979, 19.0402,
     "https://www.elelmiszerbank.hu",
     "Hungarian food bank association providing emergency food and basic needs to people in crisis, supported by a nationwide volunteer (önkéntes) network. Magyar Élelmiszerbank",
     "88.99"),
    ("Česká federace potravinových bank", "CZ", "Prague", 50.0755, 14.4378,
     "https://www.potravinovebanky.cz",
     "Czech federation of potravinová banka food banks coordinating emergency food and basic needs distribution via a volunteer (dobrovolník) network. Česká federace potravinových bank",
     "88.99"),
    ("Potravinová banka Slovenska", "SK", "Bratislava", 48.1486, 17.1077,
     "https://potravinovabanka.sk",
     "Slovak food bank providing emergency food and basic needs to charities across Slovakia with a volunteer (dobrovoľník) response network. Potravinová banka Slovenska",
     "88.99"),
    ("Eesti Toidupank", "EE", "Tallinn", 59.437, 24.7536,
     "https://toidupank.ee",
     "Estonian food bank (toidupank) providing emergency food parcels and basic needs to people in crisis with a volunteer (vabatahtlik) network. Eesti Toidupank",
     "88.99"),
    ("Latvijas Pārtikas banka Paēdušai Latvijai", "LV", "Riga", 56.9496, 24.1052,
     "https://www.paedusailatvijai.lv",
     "Latvian food bank providing emergency food and basic needs to families in crisis through a volunteer (brīvprātīgais) network across Latvia. Paēdušai Latvijai",
     "88.99"),
    ("Maisto bankas", "LT", "Vilnius", 54.6872, 25.2797,
     "https://www.maistobankas.lt",
     "Lithuanian food bank delivering emergency food and basic needs to people in crisis with a volunteer (savanoris) response network. Maisto bankas",
     "88.99"),
    ("Food Bank Ireland (FoodCloud)", "IE", "Dublin", 53.3498, -6.2603,
     "https://food.cloud",
     "Irish national food bank redistributing surplus food as emergency food aid and basic needs supplies through a volunteer network. FoodCloud",
     "88.99"),
    ("The Trussell Trust", "UK", "Salisbury", 51.0688, -1.7945,
     "https://www.trusselltrust.org",
     "Network of over 1,300 UK food bank centres providing emergency food and basic needs to people in crisis, supported by volunteers. The Trussell Trust",
     "88.99"),
    ("FareShare", "UK", "London", 51.5074, -0.1278,
     "https://fareshare.org.uk",
     "UK charity redistributing surplus food as emergency food and basic needs to 8,500 frontline charities and community groups via volunteer networks. FareShare",
     "88.99"),
    ("Boroume (Μπορούμε)", "GR", "Athens", 37.9838, 23.7275,
     "https://www.boroume.gr",
     "Greek non-profit saving surplus food and delivering it as emergency food and basic needs to people in crisis through a volunteer (εθελοντής) network. Boroume",
     "88.99"),
    ("Banca pentru Alimente", "RO", "Bucharest", 44.4268, 26.1025,
     "https://bancapentrualimente.ro",
     "Romanian food bank (banca pentru alimente) providing emergency food and basic needs to charities and beneficiaries with a volunteer (voluntar) network. Federația Băncilor pentru Alimente",
     "88.99"),
    ("Hrvatska mreža banaka hrane", "HR", "Zagreb", 45.815, 15.9819,
     "https://www.bankahrane.hr",
     "Croatian food bank network providing emergency food and basic needs to people in crisis with a volunteer (volonter) response. Hrvatska mreža banaka hrane",
     "88.99"),
    ("Slovenska filantropija – Food bank programme", "SI", "Ljubljana", 46.0569, 14.5058,
     "https://www.filantropija.org",
     "Slovenian charity coordinating emergency food and basic needs distribution plus community-based volunteer response for people in crisis. Slovenska filantropija",
     "88.99"),
    ("Foodbank Malta Foundation", "MT", "Qormi", 35.8756, 14.4728,
     "https://foodbank.org.mt",
     "Maltese food bank distributing emergency food and basic needs to families in crisis with a volunteer response network. Foodbank Malta",
     "88.99"),
    ("Stëmm vun der Strooss", "LU", "Luxembourg", 49.6116, 6.1319,
     "https://stemm.lu",
     "Luxembourg charity providing emergency food, basic needs (basisbehoeften) and shelter support to people in crisis with a volunteer (bénévole) team. Stëmm vun der Strooss",
     "88.99"),
    ("Matmissionen (Stockholms Stadsmission)", "SE", "Stockholm", 59.3293, 18.0686,
     "https://www.stadsmissionen.se",
     "Swedish social food bank (matbank) providing emergency food and basic needs to people in crisis with a volunteer (frivillig) network. Stockholms Stadsmission",
     "88.99"),
    ("Matsentralen Norge", "NO", "Oslo", 59.9139, 10.7522,
     "https://matsentralen.no",
     "Norwegian food bank network redistributing surplus food as emergency food and basic needs through a volunteer (frivillig) response. Matsentralen Norge",
     "88.99"),
    ("FødevareBanken", "DK", "Copenhagen", 55.6761, 12.5683,
     "https://foedevarebanken.dk",
     "Danish food bank providing emergency food and basic needs to social organisations with a volunteer (frivillig) network across Denmark. FødevareBanken",
     "88.99"),
    ("Ruoka-apu / Finnish food aid network", "FI", "Helsinki", 60.1699, 24.9384,
     "https://ruoka-apu.fi",
     "Finnish food aid coordinator delivering emergency food and basic needs parcels through a volunteer (vapaaehtoinen) network across Finland. Ruoka-apu",
     "88.99"),
    ("Wiener Tafel", "AT", "Vienna", 48.2082, 16.3738,
     "https://www.wienertafel.at",
     "Austrian Tafel food bank saving surplus food and distributing emergency food and basic needs to charities through a volunteer (freiwillig) network. Wiener Tafel",
     "88.99"),
    ("Fédération Belge des Banques Alimentaires (shared member)", "BE", "Brussels", 50.8459, 4.3517,
     "https://foodbanks.be",
     "Federation coordinating Belgian banque alimentaire food banks at the regional and federal level, delivering emergency food and basic needs through volunteers. FBBA",
     "88.99"),

    # ----- Shelter & evacuation -----
    ("ShelterBox", "UK", "Truro", 50.2632, -5.051,
     "https://www.shelterbox.org",
     "International disaster relief charity delivering emergency shelter, evacuation kits and essential supplies to families displaced by disasters and conflict. ShelterBox",
     "88.99"),
    ("Shelter (National Campaign for Homeless People)", "UK", "London", 51.5338, -0.1059,
     "https://england.shelter.org.uk",
     "UK housing and homelessness charity providing emergency shelter, advice and legal support to people in crisis and victims of domestic violence. Shelter",
     "88.99"),
    ("Crisis UK", "UK", "London", 51.5237, -0.08,
     "https://www.crisis.org.uk",
     "UK national charity for homeless people providing emergency shelter, crisis intervention and psychosocial support through a volunteer network. Crisis",
     "88.99"),
    ("Simon Community Ireland", "IE", "Dublin", 53.3498, -6.2603,
     "https://www.simon.ie",
     "Irish charity providing emergency shelter and opvang, basic needs and psychosocial support to homeless people in crisis, with a large volunteer network. Simon Community",
     "88.99"),
    ("Fédération des acteurs de la solidarité (FAS)", "FR", "Paris", 48.8655, 2.3429,
     "https://www.federationsolidarite.org",
     "French federation of emergency shelter (hébergement d'urgence) and evacuation providers, coordinating crisis accommodation for people in need through bénévole and professional staff. FAS",
     "88.99"),
    ("SAMU Social de Paris", "FR", "Paris", 48.8534, 2.3488,
     "https://www.samusocial.paris",
     "Paris emergency outreach service providing mobile crisis response, emergency shelter and evacuation for homeless people through a 115 helpline. Samu Social",
     "88.99"),
    ("Bundesarbeitsgemeinschaft Wohnungslosenhilfe (BAG W)", "DE", "Berlin", 52.52, 13.405,
     "https://www.bagw.de",
     "German federal working group on homelessness coordinating emergency shelter (Notunterkunft), evacuation and crisis support for people without homes. BAG Wohnungslosenhilfe",
     "88.99"),
    ("FEANTSA", "BE", "Brussels", 50.85, 4.35,
     "https://www.feantsa.org",
     "European federation of national organisations working with homeless people, coordinating emergency shelter and crisis response policy across the EU. FEANTSA",
     "88.99"),
    ("Fio.PSD (Italian homelessness federation)", "IT", "Rome", 41.9028, 12.4964,
     "https://www.fiopsd.org",
     "Italian federation for homeless services providing emergency shelter (rifugio), evacuation and crisis response through volunteer (volontario) and professional teams. fio.PSD",
     "88.99"),
    ("Asociación RAIS / Hogar Sí", "ES", "Madrid", 40.4168, -3.7038,
     "https://hogarsi.org",
     "Spanish NGO providing emergency shelter (refugio), evacuation and crisis response for homeless people, with a volunteer (voluntario) network. Hogar Sí",
     "88.99"),
    ("De Regenboog Groep", "NL", "Amsterdam", 52.3676, 4.9041,
     "https://www.deregenboog.org",
     "Amsterdam charity providing emergency shelter and opvang, basic needs and psychosocial support for homeless people, run by volunteers (vrijwilliger). De Regenboog Groep",
     "88.99"),
    ("Leger des Heils (Salvation Army Netherlands)", "NL", "Almere", 52.375, 5.2144,
     "https://www.legerdesheils.nl",
     "Dutch Salvation Army providing emergency shelter (opvang), basic needs, disaster relief and volunteer crisis response across the Netherlands. Leger des Heils",
     "88.99"),
    ("The Salvation Army – Emergency Services UK", "UK", "London", 51.5142, -0.1009,
     "https://www.salvationarmy.org.uk",
     "UK Salvation Army emergency response team providing crisis shelter, evacuation catering, basic needs and volunteer disaster relief during incidents and floods. Salvation Army",
     "88.99"),
    ("Heilsarmee Schweiz (Salvation Army Switzerland)", "CH", "Bern", 46.9481, 7.4474,
     "https://www.heilsarmee.ch",
     "Swiss Salvation Army providing emergency shelter (Notunterkunft), basic needs and volunteer (freiwillig) crisis response for people in need. Heilsarmee Schweiz",
     "88.99"),

    # ----- Psychosocial support / crisis lines -----
    ("Samaritans", "UK", "Ewell", 51.3505, -0.2498,
     "https://www.samaritans.org",
     "UK and Ireland helpline charity providing 24/7 crisis line emotional support, suicide prevention and psychosocial support through trained volunteers. Samaritans",
     "88.99"),
    ("Samaritans Ireland", "IE", "Dublin", 53.3498, -6.2603,
     "https://www.samaritans.org/ireland",
     "Irish branch of Samaritans offering 24/7 crisis helpline, suicide prevention and psychosocial support through a volunteer network. Samaritans Ireland",
     "88.99"),
    ("113 Zelfmoordpreventie", "NL", "Amsterdam", 52.3676, 4.9041,
     "https://www.113.nl",
     "Dutch national suicide prevention helpline providing 24/7 crisis line, psychosocial support and online counselling. Stichting 113",
     "88.99"),
    ("TelefonSeelsorge Deutschland", "DE", "Berlin", 52.5065, 13.1445,
     "https://www.telefonseelsorge.de",
     "German national helpline network providing 24/7 crisis line, suicide prevention counselling and psychosocial support through trained volunteers (Ehrenamtliche). TelefonSeelsorge",
     "88.99"),
    ("Tele-Onthaal (Flanders crisis helpline)", "BE", "Antwerp", 51.2194, 4.4025,
     "https://www.tele-onthaal.be",
     "Flemish 24/7 crisis helpline offering hulplijn psychosocial support and counselling through trained volunteers (vrijwilliger). Tele-Onthaal",
     "88.99"),
    ("Télé-Accueil Bruxelles", "BE", "Brussels", 50.8503, 4.3517,
     "https://www.tele-accueil.be",
     "French-speaking Belgian 24/7 crisis helpline providing psychosocial support and suicide prevention counselling through bénévole volunteers. Télé-Accueil",
     "88.99"),
    ("SOS Amitié", "FR", "Paris", 48.8566, 2.3522,
     "https://www.sos-amitie.com",
     "French national 24/7 crisis helpline offering psychosocial support, suicide prevention counselling and victim support through bénévole volunteers. SOS Amitié",
     "88.99"),
    ("Telefono Amico Italia", "IT", "Milan", 45.4642, 9.19,
     "https://www.telefonoamico.it",
     "Italian helpline offering 24/7 crisis line, psychosocial support and suicide prevention counselling through volontario volunteers. Telefono Amico Italia",
     "88.99"),
    ("Teléfono de la Esperanza", "ES", "Madrid", 40.4168, -3.7038,
     "https://telefonodelaesperanza.org",
     "Spanish crisis helpline providing 24/7 psychosocial support, suicide prevention counselling and mental health crisis response through voluntario volunteers. Teléfono de la Esperanza",
     "88.99"),
    ("Kirkens SOS", "NO", "Oslo", 59.9139, 10.7522,
     "https://www.kirkens-sos.no",
     "Norwegian 24/7 crisis line providing psychosocial support, suicide prevention counselling and grief support through frivillig volunteers. Kirkens SOS",
     "88.99"),
    ("Mind Sverige (suicide prevention helpline)", "SE", "Stockholm", 59.3293, 18.0686,
     "https://mind.se",
     "Swedish suicide prevention charity operating national crisis helplines and psychosocial support services through frivillig volunteers. Mind",
     "88.99"),
    ("Livslinien", "DK", "Copenhagen", 55.6761, 12.5683,
     "https://www.livslinien.dk",
     "Danish national suicide prevention crisis line providing psychosocial support and counselling through frivillig volunteers. Livslinien",
     "88.99"),
    ("MIELI Suomen Mielenterveys ry", "FI", "Helsinki", 60.1699, 24.9384,
     "https://mieli.fi",
     "Finnish mental health association operating national crisis line, suicide prevention, psychosocial support and trauma counselling with vapaaehtoinen volunteers. MIELI ry",
     "88.99"),
    ("Pieaugušo un Bērnu Uzticības tālrunis (Skalbes crisis line)", "LV", "Riga", 56.9496, 24.1052,
     "https://www.skalbes.lv",
     "Latvian 24/7 crisis helpline providing psychosocial support, suicide prevention and victim support counselling through brīvprātīgais volunteers. Skalbes",
     "88.99"),
    ("Jaunimo linija (Youth crisis line)", "LT", "Kaunas", 54.8985, 23.9036,
     "https://jaunimolinija.lt",
     "Lithuanian youth crisis helpline providing psychosocial support, suicide prevention and mental health counselling through savanoris volunteers. Jaunimo linija",
     "88.99"),
    ("Nightline Association Europe (student crisis lines)", "UK", "Oxford", 51.7520, -1.2577,
     "https://www.nightline.ac.uk",
     "Federation of student-run university crisis helplines across the UK, Ireland and Europe providing nightly psychosocial support and counselling through volunteer teams. Nightline",
     "88.99"),
    ("Modrá linka (Czech crisis line)", "CZ", "Brno", 49.1951, 16.6068,
     "https://www.modralinka.cz",
     "Czech 24/7 crisis helpline for children and adults providing psychosocial support, suicide prevention and trauma counselling through dobrovolník volunteers. Modrá linka",
     "88.99"),
    ("Linia Zaufania dla Dzieci i Młodzieży 116 111", "PL", "Warsaw", 52.2297, 21.0122,
     "https://116111.pl",
     "Polish child and youth crisis helpline providing psychosocial support, suicide prevention and counselling through trained wolontariusz volunteers. Fundacja Dajemy Dzieciom Siłę",
     "88.99"),
    ("Κέντρο Ημέρας Νόστος / Klimaka SOS helpline", "GR", "Athens", 37.9838, 23.7275,
     "https://www.klimaka.org.gr",
     "Greek suicide prevention helpline and psychosocial support service responding to people in mental health crisis with εθελοντής volunteers. Klimaka",
     "88.99"),
    ("Slachtofferhulp Nederland", "NL", "Utrecht", 52.0907, 5.1214,
     "https://www.slachtofferhulp.nl",
     "Dutch national victim support charity providing psychosocial support, crisis response and counselling for victims of crime, accidents and disasters through vrijwilliger volunteers. Slachtofferhulp",
     "88.99"),
    ("Weisser Ring e.V.", "DE", "Mainz", 49.9929, 8.2473,
     "https://www.weisser-ring.de",
     "German national victim support association providing psychosocial support, crisis counselling and assistance to victims of crime and domestic violence through Ehrenamtliche volunteers. Weisser Ring",
     "88.99"),
    ("France Victimes", "FR", "Paris", 48.8566, 2.3522,
     "https://www.france-victimes.fr",
     "French national federation for victim support (victim support) providing psychosocial support, crisis counselling and legal aid to victims of crime and domestic violence. France Victimes",
     "88.99"),

    # ----- Volunteer response & community resilience -----
    ("Team Rubicon UK", "UK", "London", 51.5074, -0.1278,
     "https://teamrubicon.org.uk",
     "UK volunteer-led disaster relief and emergency response organisation deploying military veterans and civilian volunteers to floods and crises. Team Rubicon UK",
     "88.99"),
    ("British Red Cross – Emergency Response", "UK", "London", 51.5285, -0.1013,
     "https://www.redcross.org.uk",
     "UK Red Cross humanitarian emergency response teams providing disaster relief, evacuation support, shelter assistance and crisis response through a volunteer network. British Red Cross",
     "88.99"),
    ("Det Frivillige Beredskabsforbund (Danish civil protection volunteer league)", "DK", "Hedehusene", 55.6496, 12.1936,
     "https://www.beredskabsforbundet.dk",
     "Danish civil protection volunteer (frivillig) league supporting rescue, evacuation and disaster relief operations in crisis situations. Beredskabsforbundet",
     "88.99"),
    ("Norsk Folkehjelp (Norwegian People's Aid)", "NO", "Oslo", 59.9139, 10.7522,
     "https://www.folkehjelp.no",
     "Norwegian humanitarian organisation providing search and rescue, disaster relief, shelter and volunteer (frivillig) crisis response across Norway and abroad. Norsk Folkehjelp",
     "88.99"),
    ("Frivillige organisasjoners redningsfaglige forum (FORF)", "NO", "Oslo", 59.9139, 10.7522,
     "https://www.forf.no",
     "Norwegian umbrella of voluntary search and rescue (redning) organisations coordinating frivillig crisis response across mountains, water and urban areas. FORF",
     "88.99"),
    ("Sveriges Civilförsvarsförbund", "SE", "Stockholm", 59.3293, 18.0686,
     "https://www.civil.se",
     "Swedish civil protection volunteer (frivillig) association training people for crisis response, evacuation and community resilience in peacetime emergencies. Sveriges Civilförsvarsförbund",
     "88.99"),
    ("Frivilliga Resursgruppen (FRG)", "SE", "Stockholm", 59.3293, 18.0686,
     "https://www.civil.se/frg",
     "Swedish municipal volunteer (frivillig) resource group supporting emergency services in evacuation, shelter and crisis response operations. FRG",
     "88.99"),
    ("Suomen Pelastusalan Keskusjärjestö (SPEK)", "FI", "Helsinki", 60.1699, 24.9384,
     "https://www.spek.fi",
     "Finnish central rescue and civil protection organisation coordinating volunteer (vapaaehtoinen) fire and rescue units and community resilience training. SPEK",
     "88.99"),
    ("Vabatahtlik Merepääste (Estonian volunteer sea rescue)", "EE", "Tallinn", 59.437, 24.7536,
     "https://merepaaste.ee",
     "Estonian volunteer (vabatahtlik) maritime search and rescue organisation responding to distress at sea around the Baltic coast. Vabatahtlik Merepääste",
     "88.99"),
    ("Stichting Samenwerkende Hulporganisaties (Giro555)", "NL", "The Hague", 52.0705, 4.3007,
     "https://giro555.nl",
     "Dutch joint humanitarian emergency appeal coordinating 11 humanitarian NGOs for disaster relief, shelter and crisis response abroad. Giro555 / SHO",
     "88.99"),
    ("Ready2Help (Rode Kruis volunteer network)", "NL", "The Hague", 52.0705, 4.3007,
     "https://www.rodekruis.nl/ready2help",
     "Dutch Red Cross flash volunteer (vrijwilliger) network mobilising community-based crisis response for floods, evacuations and local emergencies. Rode Kruis Ready2Help",
     "88.99"),
    ("Buurthulp Nederland (neighbourhood response network)", "NL", "Amsterdam", 52.3676, 4.9041,
     "https://www.buurthulp.nl",
     "Dutch neighbourhood (buurthulp) volunteer network supporting vulnerable residents with basic needs, community resilience and crisis preparedness. Buurthulp",
     "88.99"),
    ("Croix-Rouge française – Urgence et Secourisme", "FR", "Paris", 48.8439, 2.3108,
     "https://www.croix-rouge.fr",
     "French Red Cross emergency and first-aid services providing humanitarian disaster relief, evacuation support, shelter and bénévole volunteer crisis response. Croix-Rouge française",
     "88.99"),
    ("Protection Civile – Fédération nationale", "FR", "Paris", 48.8566, 2.3522,
     "https://www.protection-civile.org",
     "French national federation of protection civile associations providing volunteer civil protection, first aid, evacuation and disaster relief across France. FNPC",
     "88.99"),
    ("Bundesanstalt Technisches Hilfswerk (THW) Volunteer Network", "DE", "Bonn", 50.7374, 7.0982,
     "https://www.thw.de",
     "German federal civil protection agency with 80,000 freiwillig volunteers providing technical disaster relief, evacuation, shelter and search and rescue operations. THW",
     "88.99"),
    ("Arbeiter-Samariter-Bund Deutschland (ASB)", "DE", "Cologne", 50.9375, 6.9603,
     "https://www.asb.de",
     "German humanitarian ehrenamtlich association providing emergency medical services, disaster relief, evacuation support and crisis response across Germany. ASB",
     "88.99"),
    ("Johanniter-Unfall-Hilfe e.V.", "DE", "Berlin", 52.52, 13.405,
     "https://www.johanniter.de",
     "German humanitarian organisation with large freiwillig volunteer base providing disaster relief, emergency medical services, evacuation and psychosocial support. Johanniter",
     "88.99"),
    ("Malteser Hilfsdienst", "DE", "Cologne", 50.9375, 6.9603,
     "https://www.malteser.de",
     "German humanitarian relief service (Malteser) providing disaster relief, evacuation, emergency shelter and volunteer (freiwillig) crisis response nationwide. Malteser Hilfsdienst",
     "88.99"),
    ("Misericórdias de Portugal", "PT", "Lisbon", 38.7223, -9.1393,
     "https://www.ump.pt",
     "Portuguese national union of Misericórdias providing humanitarian disaster relief, emergency shelter, basic needs and voluntário crisis response in local communities. UMP",
     "88.99"),
    ("Croce Rossa Italiana – Volontari", "IT", "Rome", 41.9028, 12.4964,
     "https://cri.it",
     "Italian Red Cross volontario volunteer network providing humanitarian disaster relief, search and rescue, shelter assistance and psychosocial support. Croce Rossa Italiana",
     "88.99"),
    ("Cruz Roja Española – Emergencias", "ES", "Madrid", 40.4168, -3.7038,
     "https://www.cruzroja.es",
     "Spanish Red Cross humanitarian emergency response providing disaster relief, search and rescue, evacuation support and voluntario crisis response. Cruz Roja",
     "88.99"),
    ("DYA (Detente y Ayuda – Basque volunteer rescue)", "ES", "Bilbao", 43.263, -2.9349,
     "https://www.dya.es",
     "Spanish voluntary (voluntario) emergency response organisation providing first aid, rescue, evacuation and civil protection services in the Basque Country. DYA",
     "88.99"),
    ("Caritas Europa", "BE", "Brussels", 50.8503, 4.3517,
     "https://www.caritas.eu",
     "European humanitarian Catholic network coordinating disaster relief, emergency shelter, basic needs and volunteer crisis response across 49 national Caritas members. Caritas Europa",
     "88.99"),
    ("Magyar Máltai Szeretetszolgálat", "HU", "Budapest", 47.4979, 19.0402,
     "https://www.maltai.hu",
     "Hungarian Maltese charity service (Máltai) providing humanitarian disaster relief, emergency shelter, basic needs and önkéntes volunteer crisis response nationally. Magyar Máltai Szeretetszolgálat",
     "88.99"),
    ("ADRA Europe", "CZ", "Prague", 50.0755, 14.4378,
     "https://adraeurope.org",
     "Humanitarian NGO network coordinating disaster relief, emergency shelter, basic needs and dobrovolník volunteer crisis response across European countries. ADRA Europe",
     "88.99"),
    ("Habitat for Humanity International – European office", "SK", "Bratislava", 48.1486, 17.1077,
     "https://www.habitat.org/emea",
     "International NGO providing emergency shelter, evacuation housing support and community resilience programmes after disasters across Europe, Middle East and Africa. Habitat for Humanity EMEA",
     "88.99"),
    ("Caritas Austria – Notfallhilfe", "AT", "Vienna", 48.2082, 16.3738,
     "https://www.caritas.at",
     "Austrian Caritas humanitarian relief division providing disaster relief, emergency shelter (Notunterkunft), basic needs and freiwillig volunteer crisis response. Caritas Österreich",
     "88.99"),
    ("Samaritan Bund Österreich", "AT", "Vienna", 48.2082, 16.3738,
     "https://www.samariterbund.net",
     "Austrian humanitarian freiwillig volunteer organisation providing emergency medical services, disaster relief and evacuation support nationwide. Arbeiter-Samariter-Bund Österreich",
     "88.99"),
    ("Landesfeuerwehrverband (Austrian volunteer fire umbrella)", "AT", "Vienna", 48.2082, 16.3738,
     "https://www.bundesfeuerwehrverband.at",
     "Austrian federal association of freiwillig volunteer fire brigades (Feuerwehr) providing fire rescue, civil protection and disaster relief across the country. Österreichischer Bundesfeuerwehrverband",
     "88.99"),
    ("Crveni križ Srbije-supporting network in Croatia: Hrvatski Crveni križ Mladi", "HR", "Zagreb", 45.815, 15.9819,
     "https://www.hck.hr",
     "Croatian Red Cross (Crveni križ) youth volunteer (volonter) network providing humanitarian disaster relief, first aid, shelter support and psychosocial support. Hrvatski Crveni križ",
     "88.99"),
    ("Rdeči križ Slovenije – Mladi in prostovoljci", "SI", "Ljubljana", 46.0569, 14.5058,
     "https://www.rdecikriz.si",
     "Slovenian Red Cross youth and prostovoljec (volunteer) network delivering humanitarian disaster relief, shelter and psychosocial support in crisis situations. Rdeči križ Slovenije",
     "88.99"),
    ("Maltai Hungary Emergency Response Teams", "HU", "Budapest", 47.5, 19.05,
     "https://www.maltai.hu/katasztrofa",
     "Hungarian Máltai emergency and disaster relief unit providing evacuation, emergency shelter and önkéntes volunteer crisis response during floods and major incidents. Magyar Máltai Szeretetszolgálat Mentőszolgálat",
     "88.99"),

    # ----- Community resilience / neighbourhood / preparedness -----
    ("Community Resilience Development Framework (Scottish Government partners)", "UK", "Edinburgh", 55.9533, -3.1883,
     "https://ready.scot",
     "Ready Scotland community resilience programme supporting neighbourhood preparedness, volunteer response and local crisis response plans. Ready Scotland",
     "88.99"),
    ("British Red Cross – Community Resilience Programme", "UK", "London", 51.5285, -0.1013,
     "https://www.redcross.org.uk/about-us/what-we-do/emergency-response",
     "British Red Cross community resilience and neighbourhood preparedness programme building local volunteer response to floods and crises. British Red Cross Community Resilience",
     "88.99"),
    ("Stichting Nederland Veerkracht (community resilience)", "NL", "Utrecht", 52.0907, 5.1214,
     "https://nederlandveerkracht.nl",
     "Dutch community resilience foundation supporting neighbourhood (buurthulp) networks, basisbehoeften support and volunteer crisis response at local level. Nederland Veerkracht",
     "88.99"),
    ("Resilienzzentrum Österreich", "AT", "Vienna", 48.2082, 16.3738,
     "https://www.resilienzzentrum.at",
     "Austrian community resilience centre training neighbourhoods, schools and freiwillig volunteers for psychosocial support and crisis response. Resilienzzentrum Österreich",
     "88.99"),
    ("CERV Citizen Resilience Network (Polish Humanitarian Action partner)", "PL", "Warsaw", 52.2297, 21.0122,
     "https://www.pah.org.pl",
     "Polish community resilience and humanitarian aid programme building neighbourhood preparedness and wolontariusz volunteer crisis response. PAH Odporność",
     "88.99"),
    ("Fondazione Italia Resiliente", "IT", "Milan", 45.4642, 9.19,
     "https://www.italiaresiliente.it",
     "Italian community resilience (resilienza di comunità) foundation supporting neighbourhood preparedness and volontario volunteer crisis response. Italia Resiliente",
     "88.99"),
    ("Asociación Española de Resiliencia Comunitaria", "ES", "Madrid", 40.4168, -3.7038,
     "https://www.resilienciacomunitaria.es",
     "Spanish community resilience (resiliencia comunitaria) association training neighbourhoods and voluntario volunteers in crisis response and psychosocial support. AERC",
     "88.99"),
    ("SOS-Cyprus Crisis Centre", "CY", "Nicosia", 35.1856, 33.3823,
     "https://sos116111.com.cy",
     "Cypriot crisis centre providing psychosocial support, domestic violence counselling and victim support for people in crisis. SOS 1455",
     "88.99"),
    ("Български Червен кръст (Bulgarian Red Cross – Volunteer Youth)", "BG", "Sofia", 42.6977, 23.3219,
     "https://www.redcross.bg",
     "Bulgarian Red Cross (Червен кръст) volunteer youth network providing humanitarian disaster relief, first aid, shelter support and community resilience. Български Червен кръст",
     "88.99"),
    ("Asociația de Voluntari SMURD", "RO", "Târgu Mureș", 46.5407, 24.5577,
     "https://www.smurd.ro",
     "Romanian association of voluntar volunteers supporting SMURD emergency medical rescue, evacuation and crisis response operations. Asociația SMURD",
     "88.99"),
    ("Stowarzyszenie Sąsiedzkie Wsparcie Kryzysowe", "PL", "Kraków", 50.0647, 19.945,
     "https://www.pomocsasiedzka.pl",
     "Polish neighbourhood crisis support association coordinating local wolontariusz volunteers for community resilience, basic needs and psychosocial support. Sąsiedzkie Wsparcie",
     "88.99"),
]


def norm_name(n: str) -> str:
    return " ".join(n.split()).lower()


def main() -> int:
    data = json.loads(DATA.read_text(encoding="utf-8"))
    existing = {(o.get("country"), norm_name(o.get("name", ""))) for o in data}

    added = 0
    skipped = 0
    for name, cc, city, lat, lon, website, desc, nace in NEW_ORGS:
        key = (cc, norm_name(name))
        if key in existing:
            skipped += 1
            continue
        cn = COUNTRY_NAMES.get(cc)
        if not cn:
            raise SystemExit(f"Unknown country code: {cc}")
        en, local, fr = cn
        org = {
            "name": name,
            "sector_normalized": "Emergency & Crisis Response",
            "city": city,
            "country": cc,
            "country_name_en": en,
            "country_name_local": local,
            "country_name_fr": fr,
            "description_en": desc,
            "website": website,
            "lat": float(lat),
            "lon": float(lon),
            "nace_code": nace,
        }
        data.append(org)
        existing.add(key)
        added += 1

    DATA.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")
    print(f"Added {added} organisations (skipped {skipped} duplicates)")

    # Run the canonical tagger so secondary_tags are applied deterministically.
    print("\n--- Running tag_emergency_orgs.py ---")
    res = subprocess.run(
        [sys.executable, str(REPO / "scripts" / "tag_emergency_orgs.py")],
        cwd=str(REPO),
    )
    return res.returncode


if __name__ == "__main__":
    sys.exit(main())
